export { default as Advantages} from './advantages/Advantages'
export { default as Destinations} from './destinations/Destinations'
export { default as Discover} from './discover/Discover'
export { default as Feedback} from './feedback/Feedback'
export { default as Footer} from './footer/Footer'
export { default as Header} from './header/Header'
export {default as HowItWorks} from './howitworks/HowItWorks'