export { default as Discover} from './discover/Discover'
export { default as Footer} from './footer/Footer'
export { default as Header} from './header/Header'
export {default as HowItWorks} from './howitworks/HowItWorks'
export {default as Contact} from './contact/Contact'